### PR TITLE
Social links and custom files

### PR DESCRIPTION
**Pull request by marbink**
- Added social links (Facebook, Twitter, Discord & Telegram) near location button. Each social has its own config entry in config.py. [Many thanks Chrales]
- Added custom files handling (css, js & html) to help users to `git pull` without affecting frontend edits.
- [Update] Removed static css & js code from template file. Created main.css and main.js.

img

### CODE REVIEW

**Comment by beloware** [comment]
Looks cool. I will give it a try tomorow.

**Comment by thordurk91** [comment]
+1 Great way to introduce twitter notifications to users.

**Comment by beloware** [comment]
Installed. Works great. Anyway a donation button to add ? :)

**Comment by beloware** [comment]
Working good. It looks stable! Merge it please.

**Comment by Noctem** [comment]
Thanks!

**Pull request merged**
